package example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.HashMap;

// Handler value: example.Handler
public class Handler implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse>{
  Gson gson = new GsonBuilder().setPrettyPrinting().create();

  @Override
  public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent event, Context context) {
    LambdaLogger logger = context.getLogger();

    HashMap<String, String> headers = new HashMap<String, String>();
    headers.put("Content-Type", "text/html");

    APIGatewayV2HTTPResponse response = APIGatewayV2HTTPResponse.builder()
            .withIsBase64Encoded(false)
            .withStatusCode(200)
            .withHeaders(headers)
            .withBody(
                    "<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>"+
                    "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" +
                    "</body></html>"
            )
            .build();

    // log execution details
    Util.logEnvironment(event, context, gson);
    return response;
  }
}